---
- name: python | Install basic Python software/tools on Debian-based distributions
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
      - python3-pip
      - python3-build
      - python3-setuptools
      - python3-paramiko
      - python3-virtualenv
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"
  tags: python

- name: python | Install basic Python software/tools on RHEL-based distributions
  ansible.builtin.dnf:
    name:
      - nodejs
      - npm
      - python3-pip
      - python3-build
      - python3-setuptools
      - python3-paramiko
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  tags: python

- name: python | Install basic Python pip software/tools on RHEL-based distributions
  ansible.builtin.pip:
    name:
      - virtualenv
      - pip
    state: latest
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  tags: python

- name: python | Download and install Pyright language server
  community.general.npm:
    name: pyright
    global: true
    state: present
  become: true
  tags: python
