---
- name: ansible | Install npm on Debian-based distributions
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    update_cache: true
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"
  tags: ansible

- name: ansible | Install npm on RHEL-based distributions
  ansible.builtin.dnf:
    name:
      - nodejs
      - npm
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  tags: ansible

- name: ansible | Download and install Ansible language server
  community.general.npm:
    name: ansible-language-server
    global: true
    state: present
  become: true
  tags: ansible

- name: ansible | Configure Ansible collections path for Bash
  ansible.builtin.lineinfile:
    path: >-
      {{ ansible_env.HOME }}/.bashrc
    regexp: '^export ANSIBLE_COLLECTIONS_PATH=.*'
    line: export ANSIBLE_COLLECTIONS_PATH="{{ ansible_env.HOME }}/.ansible/collections/ansible_collections"
  tags: ansible

- name: ansible | Configure Ansible collections path for ZSH
  ansible.builtin.copy:
    content: |
      export ANSIBLE_COLLECTIONS_PATH="{{ ansible_env.HOME }}/.ansible/collections/ansible_collections"
    dest: >-
      {{ ansible_env.HOME }}/.oh-my-zsh/custom/ansible.zsh
    mode: '0644'
  tags: ansible
